# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1286, 849)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(609, 252, 631, 581))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(20, 70, 601, 311))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setStyleSheet("selection-background-color:pink")
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.raise_()
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 181, 41))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 30, 1211, 191))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 40, 191, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setGeometry(QtCore.QRect(370, 40, 191, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit.setGeometry(QtCore.QRect(180, 120, 391, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(30, 124, 101, 31))
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(670, 60, 191, 101))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(940, 60, 201, 101))
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 240, 561, 601))
        self.groupBox_4.setObjectName("groupBox_4")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_4)
        self.graphicsView.setGeometry(QtCore.QRect(0, 80, 531, 521))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 30, 181, 41))
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(Form.open_filepackage)
        self.pushButton_3.clicked.connect(Form.open_file)
        self.pushButton_4.clicked.connect(Form.start)
        self.pushButton_6.clicked.connect(Form.quit)
        self.pushButton_5.clicked.connect(Form.open_picture)
        self.pushButton.clicked.connect(Form.open_data)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "打开数据文件"))
        self.groupBox_3.setTitle(_translate("Form", "萌发率统计"))
        self.pushButton_2.setText(_translate("Form", "选择文件夹（按批处理）"))
        self.pushButton_3.setText(_translate("Form", "选择文件（单个处理）"))
        self.label.setText(_translate("Form", "文件路径"))
        self.pushButton_4.setText(_translate("Form", "运行"))
        self.pushButton_6.setText(_translate("Form", "退出"))
        self.groupBox_4.setTitle(_translate("Form", "显示结果"))
        self.pushButton_5.setText(_translate("Form", "打开图片"))
